version: '3.8'

services:
  database:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "65823_jm"
    volumes:
      - ./database/data:/var/opt/mssql/data
    restart: always
      
  backend:
    build:
      context: ./backend
    ports:
      - "5000:80"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
