USE [Roll_play]
GO

INSERT INTO [dbo].Tools([name], [tool_type])
     VALUES
           ('Alchemist"s Supplies', 2),
		   ('Brewer"s supplies', 2),
		   ('Calligrapher"s Supplies', 2),
		   ('Carpenter"s Tools', 2),
		   ('Cartographer"s Tools', 2),
		   ('Cobbler"s Tools', 2),
		   ('Cook"s Utensils', 2),
		   ('Disguise kit', 1),
		   ('Forgery Kit', 1),
		   ('Glassblower"s Tools', 2),
		   ('Herbalism kit', 1),
		   ('Jeweler"s Tools', 2),
		   ('Leatherworker"s Tools', 2),
		   ('Mason"s Tools', 2),
		   ('Navigator"s Tools', 1),
		   ('Painter"s Supplies', 2),
		   ('Poisoner"s Kit', 1),
		   ('Potter"s Tools', 2),
		   ('Smith"s Tools', 2),
		   ('Thieve"s Tools', 1),
		   ('Tinker"s Tools', 2),
		   ('Weaver"s Tools', 2),
		   ('Woodcarver"s Tools', 2),
		   ('Vehicles (Land)', 3),
		   ('Vehicles (Water)', 3),
		   ('Bagpipes', 4),
		   ('Drum', 4),
		   ('Dulcimer', 4),
		   ('Flute', 4),
		   ('Horn', 4),
		   ('Lute', 4),
		   ('Lyre', 4),
		   ('Pan Flute', 4),
		   ('Shawn', 4),
		   ('Viol', 4)
GO